name = "SemidefiniteOptInterface"
uuid = "f0680fed-b2cd-5302-98f9-f4da282d86b5"
repo = "https://github.com/JuliaOpt/SemidefiniteOptInterface.jl.git"
version = "0.6.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
MathOptInterface = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
